### ISSUE TITLE
It might be good to add requried python version in readme.

### ISSUE THREAD

**Issue by shuggiejang** [cablelabs/cvp2-authentication-test-tool#1]
catt.py does not run on python 3.2. It runs well on python 3.3 or higher.

**Comment by brendanlong** [comment]
Can you post the error you get? This project isn't very complicated so hopefully I can just make it work on Python 3.2 also.

**Comment by brendanlong** [comment]
I take it back. `Popen.wait()`'s timeout argument was added in Python 3.3. I don't think it's reasonable to remove that for older Python versions, so I'll just update the readme as you suggested.

**Comment by brendanlong** [comment]
Actually, removing that timeout was fine. Going back further than 3.2 would require removing `argparse`, which I'm definitely not willing to do. The change to the README that you asked for is in commit c04ae94284f2223e70476c34c5b8d4b011a98f51.
